apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: yoness/search
          envFrom:
            - configMapRef:
                name: search-configmap
          ports:
            - containerPort: 5550